# Google Cloud Build設定ファイル
steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/clinic-chatbot:$BUILD_ID', '.']
  
  # Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/clinic-chatbot:$BUILD_ID']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
    - 'run'
    - 'deploy'
    - 'clinic-chatbot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/clinic-chatbot:$BUILD_ID'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '30s'
    - '--set-env-vars'
    - 'NODE_ENV=production'

# タイムアウト設定
timeout: 600s

# 必要な権限
options:
  logging: CLOUD_LOGGING_ONLY